name: "terraform-check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    uses: vabland/actions-templates/.github/workflows/terraform-build-workflow.yml@main
    with:
      domain-name: terraform-template
      environment: dev
      aws-region: us-east-1
      apply-terraform: false
    secrets:
      aws-env-access-key: ${{ secrets.AWS_DEV_ACCESS_KEY }}
      aws-env-secret-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
      aws-general-access-key: ${{ secrets.AWS_GENERAL_ACCESS_KEY }}
      aws-general-secret-key: ${{ secrets.AWS_GENERAL_SECRET_KEY }}